name: Super-Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Install Allure
        run: |
          sudo apt update
          sudo apt install -y allure

      - name: Run API Tests and Generate Allure Results
        run: |
          mvn clean test
          ls -la target/allure-results || echo "No Allure results found!"

      - name: Move Allure Results (If Needed)
        run: |
          if [ -d "target/allure-results" ]; then
            mv target/allure-results allure-results
          fi

      - name: Verify Allure Results Exist
        run: |
          if [ ! -d "allure-results" ] || [ -z "$(ls -A allure-results)" ]; then
            echo "❌ No Allure results found! Tests may not have executed properly."
            exit 1
          else
            echo "✅ Allure results found:"
            ls -la allure-results
          fi

      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 5
